web: mkdir -p config/jwt && openssl genpkey -algorithm RSA -out config/jwt/private.pem -pkeyopt rsa_keygen_bits:4096 && openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem && 
composer install --no-interaction --optimize-autoloader --no-dev && 
php -S 0.0.0.0:$PORT -t public